### ISSUE TITLE
"node": ">=10.9.0" engine restriction

### ISSUE THREAD

**Issue by vladimiry** [cedx/enum.js#2]
Is it really necessary? Can it be set to something like `"node": ">=8.9.4 <9 || >=10.0.0"`?

**Comment by cedx** [comment]
I doubt :smiley_cat: I'm using ES6 features but they're available with Node 8.

I'm using a `>=10.9` constraint because on most of my projects I use the global `URL` API and the `fs.promises` API (I like to live on the bleeding edge)... and I do a lot of copy/paste between those projects.

The `enum.js` does not use these features, so the engine constraint could be relaxed.

**Comment by vladimiry** [comment]
Great, since with >=10.9.0 it's not possible to use the library with for example Electron.

**Comment by cedx** [comment]
Fixed in the released version 5.1.1.

**Comment by vladimiry** [comment]
Just noted that documentation page has not got updated yet:

![docs](https://user-images.githubusercontent.com/1560781/44876513-00a48580-acaa-11e8-8f79-3891c23b6307.png)

**Comment by cedx** [comment]
Thanks ! I've also updated the online documentation and API reference. The npm package still show the old Node badge : I don't intent to release another version just to fix this issue.

**Comment by vladimiry** [comment]
Sure, thanks.
